services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PLATFORM: ${PLATFORM}
    image: lmwcode/lmw-fitness-frontend:v0.0.1
    container_name: lmw_fitness_webserver
    ports:
       - "5052:5052"
    networks:
      - lmw_fitness_network
    env_file:
      - .env.production
    volumes:
      - ./webserver/default.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-logs:/var/log/nginx
      - ./nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt:ro
      - ./nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key:ro
    restart: unless-stopped

networks:
  lmw_fitness_network:
    external: true