namespace: lmw-fitness

webserver:
  port: 5052
  type: NodePort
  nodePort: 31333
  host: www.lmwfitness.co.uk
  path: /
  pathType: Prefix
  recaptcha: 6Ldn3-0qAAAAAMWv4iekZdMl4Xrfj2Av2zEL7onD
  backendUrl: https://api.lmwfitness.co.uk

image:
  repository: lmwcode/lmw_fitness_webserver
  tag: v1.3.4
  pullPolicy: Always

replicaCount: 1

api:
  port: 8082
  path: /api/

livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 120
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 120
  failureThreshold: 3
  successThreshold: 1