namespace: lmw-fitness

webserver:
  port: 5052
  type: NodePort
  nodePort: 31333
  host: www.lmwfitness.co.uk
  path: /
  pathType: Prefix

image:
  repository: lmwcode/lmw_fitness_webserver
  tag: v1.3.0
  pullPolicy: Always

replicaCount: 1

api:
  port: 8082
  path: /api/

livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 120
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 120
  failureThreshold: 3