apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redirect
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirect
  template:
    metadata:
      labels:
        app: redirect
    spec:
      containers:
      - name: redirect
        image: arbarwings/docker-web-redirect
        env:
        - name: REDIRECT_TARGET
          value: "https://www.lmwfitness.co.uk"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redirect
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: redirect
  ports:
    - port: 80
      targetPort: 80